@startuml

start

:Посетитель заходит на веб-портал;
:Проходит аутентификации;
:Создает организатора;

split
    if (Необходимо\nсоздать мероприятие) then (Да)
        :Создает мероприятие;
    else  (Нет)
    endif
split again
    if (Необходимо\nназначить работников) then (Да)
        :Назначает работников;
    else  (Нет)
    endif
split again
    if (Необходимо выдать\nправа модератора работнику) then (Да)
        :Выдает права;
    else  (Нет)
    endif
end split

stop

@enduml