@startuml

title Отправление запроса на создание обсуждения студии/игры/оргнанизатора/события

skinparam actorStyle hollow
Actor "Клиентская\nчасть приложения" as user
Control "Серверная\nчасть приложения" as backend
Database "SQL БД" as sql
Database "Документо-\nориентированная\nNoSQL" as docdb


user -> backend : Запрос

alt данные не прошли проверку
    backend --> user : Запрос отклонён
else данные прошли проверку
    backend -> sql : Запрос на добавление данных
    alt ошибка при добавлении данных
        sql --> backend
        backend --> user : Запрос отклонён
    else данные были успешно добавлены
        sql --> backend
    end
else
    backend -> docdb : Запрос на добавление данных
    alt ошибка при добавлении данных
        docdb --> backend
        backend --> user : Запрос отклонён
    else данные были успешно добавлены
        docdb --> backend
    end
else
    backend --> user : Ответ об успешном добавлении страницы
end


@enduml
