@startuml

title Запрос на добавление/редактирование/удаление страницы организатора

state "Валидация\nданных запроса" as s2 
state "Запрос на добавление\nданных в SQL БД" as s3
state "Запрос на добавление\nданных в документо-\nориентированную" as s5

[*] --> s2 : Запрос
s2 --> [*] : Провалилась
s2 --> s3 : Прошла успешно
s3 -> [*] : Провалился
s3 --> s5 : Прошёл успешно
s5 -> [*] : Провалился
s5 ---> [*] : Прошёл успешно

@enduml
