@startuml

title "Взаимодействия организатора с системой"

skinparam actorStyle hollow
:Организатор: as organizer
top to bottom direction

usecase "Создание страницы организатора" as create_organizer_page
usecase "Создание обсуждения\nна странице организатора" as create_organizer_topic
usecase "Создание страницы события" as create_game_page
usecase "Создание обсуждения\nна странице события" as create_game_topic
usecase "Запрещение пользователю\nоставлять комментарии" as ban_comments
usecase "Запрещение пользователю\nсоздавать обсуждения" as ban_topics
usecase "Комментирование обсуждения" as comment_topic
usecase "Добавление реакции к обсуждению" as react_topic
usecase "Добавление реакции к комментарию" as react_comment

create_organizer_page -[hidden]-> create_game_page
create_game_page -[hidden]-> create_organizer_topic
create_organizer_topic -[hidden]-> create_game_topic

ban_comments -[hidden]-> ban_topics
ban_topics -[hidden]-> comment_topic
comment_topic -[hidden]-> react_topic
react_topic -[hidden]-> react_comment

organizer -up-> create_organizer_page
organizer --> create_organizer_topic
organizer -left-> create_game_page
organizer --> create_game_topic
organizer -up-> ban_comments
organizer --> ban_topics
organizer -right-> comment_topic
organizer --> react_topic
organizer --> react_comment

@enduml
